import { type FormEvent, useId, useState } from 'react';

/**
 * The Supporter Feedback form. It goes nowhere, on purpose: the reply is
 * worked out here in the browser and nothing is sent or stored (PLAN.md §1).
 * It asks for no name or contact details, so there is no personal data to
 * mishandle even by accident.
 */

const TOPICS = {
  relegation: {
    label: 'My club has been relegated',
    reply: 'Your club has not been relegated. It was not invited.',
  },
  tickets: {
    label: 'Ticket prices',
    reply: 'Your price reflected the moment. The moment has been informed of your feedback.',
  },
  offside: {
    label: 'An offside decision',
    reply: 'The decision has been reviewed by Clawed AI, which agrees with itself.',
  },
  atmosphere: {
    label: 'The atmosphere',
    reply:
      'Atmosphere is calibrated to broadcast tolerances by our venue partner. Yours has been adjusted.',
  },
  ownership: {
    label: 'Who owns my club',
    reply: 'Ownership details are available in each club’s listing document. You are not on it.',
  },
  other: {
    label: 'Something else',
    reply: 'Your concern has been matched to the most similar concern we were expecting.',
  },
} as const;

type Topic = keyof typeof TOPICS;

/** A stable reference number from the submission, so the same input gets the same reply. */
function reference(topic: string, message: string): string {
  let h = 2166136261;
  for (const ch of topic + '|' + message) h = Math.imul(h ^ ch.charCodeAt(0), 16777619);
  return `SF-${((h >>> 0) % 1_000_000).toString().padStart(6, '0')}`;
}

export function SupporterFeedback() {
  const id = useId();
  const [topic, setTopic] = useState<Topic>('relegation');
  const [message, setMessage] = useState('');
  const [reply, setReply] = useState<{ ref: string; lines: string[] } | null>(null);

  function submit(e: FormEvent) {
    e.preventDefault();
    const said = message.trim();
    setReply({
      ref: reference(topic, said),
      lines: [
        `Thank you for contacting Supporter Services about “${TOPICS[topic].label.toLowerCase()}”.`,
        said
          ? 'Your message has been received, valued and generated a response.'
          : 'We have noted that you had nothing further to add. Neither had we.',
        TOPICS[topic].reply,
        'Your concern has been escalated to the appropriate subscription tier.',
      ],
    });
  }

  return (
    <div>
      <form onSubmit={submit} className="space-y-5" aria-describedby={`${id}-note`}>
        <div>
          <label htmlFor={`${id}-topic`} className="smallcaps block text-ink-muted">
            Topic
          </label>
          <select
            id={`${id}-topic`}
            value={topic}
            onChange={(e) => setTopic(e.target.value as Topic)}
            className="mt-2 w-full border border-rule bg-surface px-3 py-2.5"
          >
            {Object.entries(TOPICS).map(([key, t]) => (
              <option key={key} value={key}>
                {t.label}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label htmlFor={`${id}-message`} className="smallcaps block text-ink-muted">
            Your feedback
          </label>
          <textarea
            id={`${id}-message`}
            rows={4}
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            className="mt-2 w-full border border-rule bg-surface px-3 py-2.5"
          />
        </div>
        <button
          type="submit"
          className="bg-navy px-6 py-3 font-semibold text-parchment hover:bg-ink"
        >
          Submit feedback
        </button>
        <p id={`${id}-note`} className="ooc rounded px-3 py-2 text-sm">
          <strong>Out of character:</strong> nothing you type here leaves your browser. The reply is
          generated on this page and nothing is stored.
        </p>
      </form>

      <div role="status" aria-live="polite" className="mt-6">
        {reply && (
          <div className="border border-rule bg-surface-2 p-6">
            <p className="smallcaps figures text-ink-muted">Reference {reply.ref}</p>
            <div className="mt-3 space-y-2">
              {reply.lines.map((l) => (
                <p key={l}>{l}</p>
              ))}
            </div>
            <p className="mt-4 text-xs text-ink-muted">Response generated by ChatGDP.</p>
          </div>
        )}
      </div>
    </div>
  );
}
