/**
 * Typed access to the game's locked canon (src/canon/game, generated by
 * scripts/import-game-canon.mjs — never hand-edited) and to the site's own
 * lore (src/canon/site).
 */
import clubLoreJson from './game/clubLore.json';
import clubsJson from './game/clubs.json';
import decreesJson from './game/decrees.json';
import domesticJson from './game/domesticLeagues.json';
import loreJson from './game/lore.json';

export interface Club {
  id: string;
  name: string;
  shortName: string;
  cardName: string;
  membership: 'permanent' | 'global';
  country: string;
  city: string;
  logo: string;
  colors: { primary: string; secondary: string };
  rivalries: string[];
}

export interface ClubLore {
  ticker: string;
  exchange: string;
  listPrice: number;
  valuationBn: number;
  tokTokFollowers: number;
  owner: string;
  positioning: string;
  history: string[];
  riskFactor: string;
}

export interface Decree {
  id: string;
  name: string;
  tagline: string;
  description: string;
  accent: string;
}

export const lore = loreJson;
export const league = {
  size: clubsJson.leagueSize,
  rotatingSlots: clubsJson.rotatingSlots,
  permanentIds: clubsJson.permanentIds,
  globalIds: clubsJson.globalIds,
};
export const clubs = clubsJson.clubs as Club[];
/**
 * Club lore as the site renders it. The site overrides in
 * site/clubOverrides.ts are applied at build time by vite.canon-overrides.ts,
 * so the game's original owner names are never bundled.
 */
export const clubLore = clubLoreJson as Record<string, ClubLore>;
export const decrees = decreesJson as Decree[];
export const domestic = domesticJson;

export const clubById = (id: string): Club | undefined => clubs.find((c) => c.id === id);
export const crestSrc = (club: Club) => `/club-crests/${club.logo}`;
/** 192px-tall thumbnail (scripts/build-thumbs.mjs), for grids. */
export const crestThumb = (club: Club) => `/club-crests/thumb/${club.logo}`;
/** 48px-tall mini, for ledger rows and chips. */
export const crestMini = (club: Club) => `/club-crests/mini/${club.logo}`;

/** `71_400_000` → `71.4M`. Same rules as the game's formatFollowers. */
export function formatFollowers(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 10_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 10_000) return `${Math.round(n / 1000)}K`;
  if (n >= 1_000) return `${(n / 1000).toFixed(1)}K`;
  return `${n}`;
}

/** Look a decree up by id. Throws on a typo, so a renamed decree fails the build. */
export function decree(id: string): Decree {
  const found = decrees.find((d) => d.id === id);
  if (!found) throw new Error(`Unknown decree: ${id}`);
  return found;
}

/** The intro reel's scenes, by id. Shapes are the game's IntroScene union, loosely typed. */
export interface IntroScene {
  id: string;
  kind: string;
  kicker?: string;
  headline?: string;
  body?: string;
  punch?: string;
  stamp?: string;
  footnote?: string;
  stats?: { value: string; label: string }[];
  filingTitle?: string;
  filing?: { label: string; value: string; redacted?: boolean }[];
  quote?: { text: string; attribution: string };
  partners?: { name: string; role: string }[];
  punchline?: string[];
  welcome?: string[];
  disclaimer?: string;
}

export function scene(id: string): IntroScene {
  const found = (lore.intro.scenes as IntroScene[]).find((s) => s.id === id);
  if (!found) throw new Error(`Unknown intro scene: ${id}`);
  return found;
}

export const clubsIn = (ids: string[]) => ids.map((id) => clubById(id)!).filter(Boolean);

export { SITE_CANON } from './site';
