/**
 * Typed access to the game's locked canon (src/canon/game, generated by
 * scripts/import-game-canon.mjs — never hand-edited) and to the site's own
 * lore (src/canon/site).
 */
import clubLoreJson from './game/clubLore.json';
import clubsJson from './game/clubs.json';
import decreesJson from './game/decrees.json';
import domesticJson from './game/domesticLeagues.json';
import loreJson from './game/lore.json';

export interface Club {
  id: string;
  name: string;
  shortName: string;
  cardName: string;
  membership: 'permanent' | 'global';
  country: string;
  city: string;
  logo: string;
  colors: { primary: string; secondary: string };
  rivalries: string[];
}

export interface ClubLore {
  ticker: string;
  exchange: string;
  listPrice: number;
  valuationBn: number;
  tokTokFollowers: number;
  owner: string;
  positioning: string;
  history: string[];
  riskFactor: string;
}

export interface Decree {
  id: string;
  name: string;
  tagline: string;
  description: string;
  accent: string;
}

export const lore = loreJson;
export const league = {
  size: clubsJson.leagueSize,
  rotatingSlots: clubsJson.rotatingSlots,
  permanentIds: clubsJson.permanentIds,
  globalIds: clubsJson.globalIds,
};
export const clubs = clubsJson.clubs as Club[];
export const clubLore = clubLoreJson as Record<string, ClubLore>;
export const decrees = decreesJson as Decree[];
export const domestic = domesticJson;

export const clubById = (id: string): Club | undefined => clubs.find((c) => c.id === id);
export const crestSrc = (club: Club) => `/club-crests/${club.logo}`;

/** `71_400_000` → `71.4M`. Same rules as the game's formatFollowers. */
export function formatFollowers(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 10_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 10_000) return `${Math.round(n / 1000)}K`;
  if (n >= 1_000) return `${(n / 1000).toFixed(1)}K`;
  return `${n}`;
}

export { SITE_CANON } from './site';
